
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2


    - name: Run a one-line script
      run: |
        npm install -g tfx-cli
        npm run build-it
        npm run pack-it

